### PR TITLE
Fix bogus path to find tbb libraries in linux

### PR DESCRIPTION
**Pull request by damianam**
TBB in linux (at least when installed as stand alone), has its libraries under `${TBB_ROOT}/lib`. `${TBB_ROOT}/lib/intel64/gcc4.4` doesn't exist, and therefore cmake fails to find TBB. `${TBB_ROOT}/libs/intel64/gcc4.4` does exist, but it seems to me like looking into `${TBB_ROOT}/lib` is a better option.

### CODE REVIEW

**Comment by johguenther** [comment]
Hi damianam,
how did you install TBB as standalone that its libraries end up in `lib`? Until now we did not see problems with `FindTBB`:
- When installed system-wide (as part of a distro) TBB is found by CMake, because CMake also searches in default system paths such as `/usr/lib`.
- When using the [TBB packages](https://github.com/01org/tbb/releases) standalone then the libraries are indeed in `lib/intel64/gcc4.4` (and not in `libs/intel64/gcc4.4`).

Best regards,
  Johannes

**Comment by damianam** [comment]
Simply with:

```
$ export INSTALL_PATH="$SWPREFIX/tbb/2017.4.174"
$ cat silent.cfg
PSET_INSTALL_DIR=$INSTALL_PATH
ACCEPT_EULA=accept
INSTALL_MODE=NONRPM
CONTINUE_WITH_OPTIONAL_ERROR=yes
ARCH_SELECTED=INTEL64

$ ./install.sh  -s silent.cfg
```

In reality it is a bit more complex because we use a framework to manage our scientific software (https://github.com/hpcugent/easybuild), we don't do it manually. But the above commands are essentially what EasyBuild does, with the exception of `PSET_INSTALL_DIR`, that is explicitly set, not using a variable.

That results in the following structure:

```
$ ls
bin  compilers_and_libraries  compilers_and_libraries_2017  compilers_and_libraries_2017.2.174  documentation_2017  easybuild  parallel_studio_xe_2017.2.050  samples_2017  tbb
```

Setting `TBB_ROOT=$INSTALL_PATH/tbb` you have:

```
$ find -L ./ -name 'libtbb\.so\.2'
./libs/ia32/gcc4.1/libtbb.so.2
./libs/ia32/gcc4.4/libtbb.so.2
./libs/ia32/gcc4.7/libtbb.so.2
./libs/intel64_lin/gcc4.1/libtbb.so.2
./libs/intel64_lin/gcc4.4/libtbb.so.2
./libs/intel64_lin/gcc4.7/libtbb.so.2
./libs/intel64/gcc4.1/libtbb.so.2
./libs/intel64/gcc4.4/libtbb.so.2
./libs/intel64/gcc4.7/libtbb.so.2
./libs/ia32_lin/gcc4.1/libtbb.so.2
./libs/ia32_lin/gcc4.4/libtbb.so.2
./libs/ia32_lin/gcc4.7/libtbb.so.2
./libs/mic/libtbb.so.2
./libs/intel64_lin_mic/libtbb.so.2
./lib/libtbb.so.2
```

**Comment by johguenther** [comment]
OK, so I guess `./lib/libtbb.so.2` is the `intel64` version? In aded1ba7 I added ` {TBB_ROOT}/lib` to the search path, I hope this is fine with you.

**Comment by damianam** [comment]
It should work, yes. Thank you.

**Pull request closed without merging**
