### PR TITLE
Changes in Transfer Function Abstraction (Cleaned)

### PR DESCRIPTION
**Pull request by wilsonCernWq**
Hi All

Recently I implemented a 2D transfer function widget using OSPRay. The widget takes gradient and scalar as inputs. In order to make the implementation easy, I had to modify some sectionsin TransferFunction class. In particular I allow transfer function to take volume and sample coordinate as inputs, instead of using one scalar value. I think this is a good change, because it then we can easily implement all kinds of multivariate transfer functions using modules.

However I haven't figured out how to handle isosurface.

Qi

### CODE REVIEW

**Comment by wilsonCernWq** [comment]
Message from Carson:

Fantastic work on the 2D transfer function Qi! I see you also added a new 1d TF widget, and it would be great if we can use that for exampleViewer. As for this merge request, it appears to contain quite a backlog of unrelated commits that were then reverted. Can you clean those out of the merge request?

**Comment by wilsonCernWq** [comment]
Message from Johannes

Indeed very interesting. Still, I like to discuss some points. I'm not sure that having the sampling coordinates as input to the transfer function is the right abstraction – this is actually the job of the volume, which maps 3D spatial coordinates to values (which can by multi-dimensional, not only scalar as currently in OSPRay). The transfer function then maps those values to color and opacity. So I agree that a scalar as input to the transfer function is not sufficient, but it should not be the coordinates. Actually, it would be nice to even generalize that further, to be able to combine multiple (potential multi-dimensional) values (from different volume) by arbitrary functions (we had some discussions about that internally, but this is obviously not trivial to implement).

**Comment by wilsonCernWq** [comment]
@carsonbrownlee There are little bit left in the new 1D TFN library. 
* I didn't implement `save` function so I cannot save a created TFN. 
* It cannot `edit` a loaded transfer function, because it will be too crazy to treat every color/opacity point in the file as a control point (There will be too many control points and it's non-trivial to simplify it). I am still thinking of a reasonable way to handle them.


@johguenther I had a discussion with Ingo before I started this project. I agree that mapping coordinate to value is volume's job. I am still thinking a better way to do this.

**Comment by carsonbrownlee** [comment]
thanks for cleaning up the merge request; however, I'm not seeing the implementation of getOpacityForCoordinate in the ispc file?  One objection I would have is re-introducing volumes into the transfer functions as params.  I separated the two before and I think it's a lot cleaner to keep them apart if it can be helped.  All a 1D transfer function should need is a sample value, or two samples for a 2D TF.  The pre-integrated TF lookups take 2 for 1D as a range of values, and I guess the 2D TF would take 4 values.  
As for 1D TFN:  The paraview colormaps we originally basing off of were control point bound already, so loading those in through the json importer Will wrote may be trivial.  Because I think having a better TF editor would be a time saver for us, I would be willing to write an exporter for it and clean it up.  Put in a separate merge request for that and I can create a branch for it if you do not have permissions to do so yourself.

**Comment by wilsonCernWq** [comment]
Hi Carson

> however, I'm not seeing the implementation of getOpacityForCoordinate in the ispc file? 

I didn't implement `getOpacityForCoordinate` and `getColorForCoordinate` in ospray source. I implemented it in my tfn module. That's why I added a flag `uniform bool queryByCoordinate` indicating if this function is implemented. The reason I did this is because I didn't want to break existing codes in other transfer function implementation. 

> All a 1D transfer function should need is a sample value, or two samples for a 2D TF. The pre-integrated TF lookups take 2 for 1D as a range of values, and I guess the 2D TF would take 4 values.

I think the problem is, if one day someone wants to implement a 3D, 4D or 5D TFN, we need to change the abstraction again and again. I think the key problem here is, we embedded the code that does the sampling inside the renderer, which means if we want to re-define how a volume samples the transfer function, we have to create a new renderer. This creates a big amount of work. It will be really nice if this part of code can be defined inside either volume or transfer function. 

>As for 1D TFN

Actually I separated all of my code in this [repo](https://github.com/wilsonCernWq/TransferFunctionModule)

```
src/TransferFunctionModule.h
src/TransferFunctionModule.cpp
```
currently are the same as tfn_lib in ospray, but I am planing to improve it.

```
src/widgets/TransferFunctionWidget.h
src/widgets/TransferFunctionWidget.cpp
```
has almost the same API as Will's transfer function. The only difference is I changed `void drawUi()` to ` bool drawUI()` which returns if this widget is opened. 

Although I have a branch which integrated this TFN inside example viewer already, I believe it will be easier if we just copy the widget code and replace it for now :D

**Comment by wilsonCernWq** [comment]
I believe this can me closed for now ~

**Pull request closed without merging**
