### PR TITLE
Separate library namelinks into devel component

### PR DESCRIPTION
**Pull request by KyleFromKitware**

### CODE REVIEW

**Comment by jeffamstutz** [comment]
@johguenther any objections to this?

**Comment by johguenther** [comment]
OK. I just don't understand the comment:  Why do static targets complain there's no ARCHIVE block? There is an ARCHIVE block also before the patch.

**Comment by KyleFromKitware** [comment]
Also, the upcoming CMake 3.12 has a `NAMELINK_COMPONENT` argument which combines this whole concept into a single `install()` command (see https://cmake.org/cmake/help/git-master/command/install.html#targets for details), but I haven't used it here because it's not recognized in older versions of CMake.

**Comment by KyleFromKitware** [comment]
Yes, you are correct. I've pushed a new version with an updated comment (worded slightly differently) and I've also rebased onto the latest devel branch.

**Comment by johguenther** [comment]
Great, thanks!

**Pull request merged**
