### PR TITLE
A small fix for making volume sampling steps consistent with each other

### PR DESCRIPTION
**Pull request by wilsonCernWq**
It is a small fix I made in my fork a while ago, where I was trying to render bricked volumes (volumes truncated into many bricks) in VisIt. I had to make the ray step consistent across all patches in order to remove seams between connected patches.

***The image before the commit***
Before Commit

***The image after the commit***
After Commit

I feel this fix can be ignored (that's why it took me a long time to open the pull request) if ospray is not designed for handling volume bricking done by application sides. But I will be happy to see it got merged since I won't have to maintain the commit myself in my fork :D

Qi

### CODE REVIEW

**Comment by jeffamstutz** [comment]
What sampling rates are you using? With your changes, I get some banding artifacts when sampling rate is < 1.0, and _really_ bad artifacts when < 0.5. It is particularly apparent with tetrahedral volumes.

See images below:

Original (no bug)
original-nobug

With your changes (banding artifact)
banding-bug

FWIW, you can test this yourself by using the ParaView "tetrahedralize" filter, then saving the data out as a ```.vtu``` file. Then you can load that into ```ospExampleViewer``` in OSPRay, just make sure you enable the ```OSPRAY_SG_VTK``` option in CMake when you build OSPRay.

**Comment by jeffamstutz** [comment]
In general, if there's a way to reconcile the two problems, I'd like to do that. Otherwise this may be something you'd have to have in a custom renderer instead.

In the future, we could make the ```scivis``` renderer more configurable, because right now it's a monolith that doesn't map well to uses outside its original purpose.

**Comment by wilsonCernWq** [comment]
I use a sampling rate = 3.0 on structured grid.
I don't feel surprising because I essentially shifted the `ray.t0` backward a little bit and `ray.t` forward a little bit, which means the next intersect volume interval can intersect with the previous interval. 

Is the "tetrahedralized" volume rendered an unstructured volume ? I will try to look at it again after I got time.

**Comment by jeffamstutz** [comment]
Yeah, a sampling rate of 3.0 is pretty high in our experience...so having options which are lower (and thus faster) would be good to preserve.

Yes, the images I showed you were taking the "wavelet" source (i.e. generated by ParaView, not a loaded dataset) which is a structured grid, ran the tetrahedralize filter, then saved the data as a ```.vtu```. This also can be done to any structured grid you load from a file.

**Comment by johguenther** [comment]
Are Visit's bricked volumes multiple volumes for OSPRay? If so, do they overlap and replicate the border voxels?

**Comment by wilsonCernWq** [comment]
They do have one layer of ghost voxels on the boundaries. Right now I can render them correctly by using this fix plus adding clipping planes inside the overlapping region (cuz we just want the volume to correctly interpolate for half voxel, clipping plane can to that).

**Comment by wilsonCernWq** [comment]
And yes, VisIt produced those bricks.

**Comment by johguenther** [comment]
Nice trick with the clipping planes to cut half a voxel :-)
It should be possible to get a solution without artifacts for both use cases, but my attempts have not been successful so far.

**Comment by wilsonCernWq** [comment]
@jeffamstutz 
Hi Jeff, 
I think the issue is caused by the low sampling rate. 
When the sampling rate is below 1.f, the defects are visible, so I added a threshold ...
It looks fine now I think
Qi

**Comment by wilsonCernWq** [comment]
I think I found a way to hack this only inside my module for my particular use case. My way is to define a bigger bounding box for the intersection, and advance the `ray.t0` multiple times inside the `stepRay` function that I defines. Although it is not clean, but at least it is working now.

I wish renderer can give volume the freedom to generate sample positions. This should be a nicer way of doing volume integration, especially when we have different volume types.

**Pull request closed without merging**
