### PR TITLE
Upgrade ImGui Version

### PR DESCRIPTION
**Pull request by wilsonCernWq**
I am implementing a better transfer function widget for ospray, which will use the new color editor introduced in ImGui 1.53.
29062188-471e95ba-7c53-11e7-9618-c4484c0b75fe
So I replaced the ImGui in example viewer and fixed bugs caused by API breaking changes.
(I have a different pull request holding there, that's why I have to revert some commits here for a separate pull request. Sorry about that.)

### CODE REVIEW

**Comment by jeffamstutz** [comment]
I saw that v1.53 was released....thanks for taking the initiative to update the viewer! Once I'm clear of some SC demo deadlines this week, I'd be happy to review/merge (as well as take a look at your updates to your other PR).

**Comment by Twinklebear** [comment]
@jeffamstutz I'd like this as well, we can use it for a demo we're showing tomorrow. I can update imgui on devel and test/push to sneak in this work

**Comment by Twinklebear** [comment]
I've merged this into devel

**Comment by wilsonCernWq** [comment]
It works great. I will close the PR :D 
screenshot from 2017-10-31 17-23-41

**Comment by jeffamstutz** [comment]
Wait, it looks like v1.52 was merged instead of v1.53? Was this intentional?

We have issues found by Klockwork, so I don't want to fix them if we are going to do another upgrade.

**Comment by Twinklebear** [comment]
1.52 is the most recent [release](https://github.com/ocornut/imgui/releases), i thought the 1.53 was a typo. The color picker is from 1.51 so we should be set

**Comment by jeffamstutz** [comment]
Yes, you are right....thanks :)

**Pull request closed without merging**
