### PR TITLE
Better 1D Transfer Function

### PR DESCRIPTION
**Pull request by wilsonCernWq**
Hi All

This is the implementation of a better 1D transfer function using imGui, which was mentioned in a different PR. I copied my repository into `apps/exampleViewer/widgets/TransferFunctionModule/ folder` after removing some unnecessary files. Then I made `apps/exampleViewer/widgets/transferFunction*` class as a wrapper class of my widget. Because in my repository I have a copy of `lib_tfn` already,  I removed the original `lib_tfn` (but didn't delete it). 

screenshot from 2018-01-30 20-47-13

My implementation is working, but there are still some features left.
* I didn't have the time to implement a `save` function for my widget, therefore we cannot save a modified transfer function yet.
* Currently once we load a transfer function file from disk, I will mark it as not [`editable`](https://github.com/wilsonCernWq/ospray/blob/tfn_PR/apps/exampleViewer/widgets/TransferFunctionModule/src/widgets/TransferFunctionWidget.h#L107) because I cannot determine what are the control points that we can use. Using all points as control points will just make the widget messy. 

Qi

### CODE REVIEW

**Comment by wilsonCernWq** [comment]
I forgot to mention that if the `save` function is implemented, we can uncomment [this](https://github.com/wilsonCernWq/ospray/blob/tfn_PR/apps/exampleViewer/widgets/TransferFunctionModule/src/widgets/TransferFunctionWidget.cpp#L149-L150) line to display the save button.

**Comment by jeffamstutz** [comment]
Hey Qi,

I've FINALLY popped enough off of my TODO list to concentrate on this. Given that this is based on an older version of OSPRay, I'm working on doing a manual "cherry-pick" of your widget and incorporating it freshly into our current stuff. I tried out the widget itself, and it is a very nice improvement over our old one!

Cheers,
Jeff

**Comment by jeffamstutz** [comment]
I'll close this PR when I've got something in ```devel```.

**Comment by jeffamstutz** [comment]
Update: I have this running in OSPRay Studio....have a look there if interested: github.com/ospray/ospray_studio

**Comment by jeffamstutz** [comment]
Also, now that OSPRay Studio exists, this widget/PR is no longer considered for OSPRay itself. We are planning on OSPRay Studio being a direct replacement to ```ospExampleViewer``` and only have minimalist tutorials that exist in the OSPRay repo itself.

Regardless, thanks @wilsonCernWq for the great widget!

**Pull request closed without merging**
