### PR TITLE
Allow disable tutorial

### PR DESCRIPTION
**Pull request by demarle**
Hope I got the flag right this time. I chose the testing flag only because of the comment.
Being protected by an APP or dedicated options instead could make more sense.

### CODE REVIEW

**Comment by jeffamstutz** [comment]
Do you want all of the apps to not be compiled, or just the tutorials? There the better option would be ```OSPRAY_ENABLE_APPS=OFF```. That would save a lot of build time. :)

**Comment by jeffamstutz** [comment]
That option will cull everything in the ```apps/``` subdirectory, including ```ospray_sg``` (which may get moved out of the repo anyway).

**Comment by johguenther** [comment]
I'm not sure I understand. `ospTutorial` servers two purposes:
- minimal example of using the API with C and C++
- catch API related build errors/warnings: this is why it is always build and cannot be disabled via `OSPRAY_ENABLE_APPS=OFF` (because it is defined in `ospray/CMakeLists.txt`)

Anyway, we also purposefully use `ADD_EXECUTABLE` instead of the `OSPRAY_CREATE_APPLICATION` macro to exclude it from installing/packaging in all cases. So, why exactly do you need to disable it?

**Comment by demarle** [comment]
Thanks for the review guys. Nor being able to turn it off is just an annoyance for me.  As a consumer of the library, I want to compile as little as possible. I can turn off apps and tests and modules etc that I don't need, but I can't turn off this executable without patching.

An example of this being an annoyance on one of the systems I am testing on:
[2/2] Linking CXX executable ospTutorialCpp
FAILED: : && /usr/bin/c++   -Wall -Wno-aligned-new -std=c++11 -fPIC -fno-strict-aliasing -Wno-narrowing -Wno-unknown-pragmas -fPIC      -std=c++11 -DNDEBUG    -O3 -Wstrict-aliasing=1 -ffast-math -fno-finite-math-only   ospray/CMakeFiles/ospTutorialCpp.dir/__/apps/ospTutorial.cpp.o  -o ospTutorialCpp  -rdynamic libospray.so.1.7.0 libospray_common.so.1.7.0 /usr/lib/x86_64-linux-gnu/libtbb.so.2 /usr/lib/x86_64-linux-gnu/libtbbmalloc.so.2 -pthread -ldl -Wl,-rpath,/home/demarle/Builds/PARAVIEW/devel/PVSB/superbuild/ospray/build && :
libospray_common.so.1.7.0: undefined reference to `tbb::interface7::internal::task_arena_base::internal_max_concurrency(tbb::interface7::task_arena const*)'
collect2: error: ld returned 1 exit status
Rather than hunt down why this configutation is linking to the wrong tbb, I just turn it off and get a perfectly usable library.

OPTION(OSPRAY_BUILD_TUTORIAL "build the hello world tutorial" ON) would also be nice.

**Comment by demarle** [comment]
Also in my case when the API changes I notice when VTK fails to compile against the library so having the tutorial for the check is nice but redundant.

**Comment by johguenther** [comment]
OK, got it. I think an advanced CMake option to skip building the tutorial is quite doable.

**Comment by johguenther** [comment]
Thank you, also for your patience.

**Pull request merged**
