### PR TITLE
Fix material memleak

### PR DESCRIPTION
**Pull request by tribal-tec**

### CODE REVIEW

**Comment by jeffamstutz** [comment]
Hi, thanks for finding this leak and creating the PR!

It turns out that we want to decrement he ```Data```, because we don't know if the material handle is something the application wants to keep around...but the ```Data``` object we create internally is something only we track. I've pushed a fix to our internal repo, and once our tests pass I'll push it back up here to GitHub.

Thanks again!

**Comment by jeffamstutz** [comment]
I'll close this once the commit makes it back to GitHub.

**Comment by tribal-tec** [comment]
Fair enough, that seems a better fix indeed!

**Comment by jeffamstutz** [comment]
Fixed in 34517843. Thanks again!

**Pull request closed without merging**
