### PR TITLE
MPI memleak fixes and optimization for FB_NONE

### PR DESCRIPTION
**Pull request by tribal-tec**

### CODE REVIEW

**Comment by tribal-tec** [comment]
Good catch, will look into this.

**Comment by tribal-tec** [comment]
Still WIP, but feel free to review. Have to test again thoroughly next week. Maybe I also find a better (or you maybe?) to de-/serialize the tile error info from/into the message.

**Comment by tribal-tec** [comment]
Ok, should be fine now.

**Comment by tribal-tec** [comment]
Ping. You have any comments for things I should address? I would like to have this integrated for the next release to make our life much easier wrt deployment.

**Comment by johguenther** [comment]
Sorry, a bit swamped right now :-/
I'll have a look tomorrow.

**Comment by tribal-tec** [comment]
No worries. Just wanted to check in to not miss this for your release :)

**Comment by johguenther** [comment]
Thanks! :-)

**Comment by tribal-tec** [comment]
Awesome! Thx for merging!

**Pull request merged**
