### PR TITLE
add an alternate search path for find tbb on windows

### PR DESCRIPTION
**Pull request by demarle**
In paraview superbuild, we tend to get tbb from a scratch
directory. This change makes sure ospray can search in that
location as well as system install places where it already looks.

Also removed unused TBB_BINDIR

### CODE REVIEW

**Comment by jeffamstutz** [comment]
Hi Dave,

Changes look good. Could you fix the merge conflict? The section in question was moved to ```cmake/ospray_options.cmake``` (where we handle installing Embree + TBB in the same place now). If you had any changes in that block, you may need to re-apply them in where they live now.

**Comment by demarle** [comment]
Will revise. Thanks.

**Comment by jeffamstutz** [comment]
Just checking, was this revised? I see commit b405170 (amended previous one it looks like). If so, I'll go ahead and merge. Sorry for the delay...

**Comment by demarle** [comment]
Yes I revised and rewrote the commit to move things into the new places and thus address the merge conflict.

**Comment by jeffamstutz** [comment]
Excellent, thanks :)

**Comment by jeffamstutz** [comment]
I suppose this means that I don't get notifications when a PR is revisted on Github...

**Comment by mathstuf** [comment]
> I suppose this means that I don't get notifications when a PR is revisted on Github...

It's possible to get it (I do at least). I see a checkbox in `Settings > Notifications > Pull Request pushes` on here.

**Comment by jeffamstutz** [comment]
Thanks for the pointer :)

**Pull request merged**
